"""nemo

Revision ID: cb59baa8a3ce
Revises: d3db579ceea4
Create Date: 2026-04-01 00:21:52.175588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb59baa8a3ce'
down_revision = 'd3db579ceea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint("m", ['_password'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
